Add integration testing for @blobscan/db
Blobscan/blobscan pull request #158
Opened 2023-08-28 04:33 UTC by 0xGabi

builds on #154

2023-08-31 22:36 UTC, PJColombo requested changes
Great work 💪!

I've left some requested changes. Some of them were created merely to identify potential areas for future adjustments. Let's defer the ones related to adding new unit tests until later.

2023-08-31 22:36 UTC, PJColombo commented on packages/api/test/indexer.test.ts
> +    it("should index new data if auth", async () => {
I think we should test the following cases as well:

1. Call the index procedure with repeated blobs as part of the input.
2. Check if the procedure is idempotent.

2023-08-31 22:36 UTC, PJColombo commented on packages/api/test/search.test.ts
> +  type Input = inferProcedureInput<AppRouter["search"]["byTerm"]>;
Let's move this outside. Type declarations should be at the beginning of the file

2023-08-31 22:36 UTC, PJColombo commented on packages/api/test/search.test.ts
> +  const caller = await getCaller();
Let's wrap this within a `beforeAll` hook

2023-08-31 22:36 UTC, PJColombo commented on packages/api/test/sync-state.test.ts
> +  const caller = await getCaller();
Let's wrap this within a `beforeAll` hook

2023-08-31 22:36 UTC, PJColombo commented on packages/api/test/tx.test.ts
> +  const caller = await getCaller();
Let's wrap this within a `beforeAll` hook

2023-08-31 22:36 UTC, PJColombo commented on packages/api/test/tx.test.ts
> +      type Input = inferProcedureInput<AppRouter["tx"]["getAll"]>;
Move type outside of describe

2023-08-31 22:36 UTC, PJColombo commented on packages/api/test/tx.test.ts
> +      type Input = inferProcedureInput<AppRouter["tx"]["getByHash"]>;
Move type outside of describe

2023-08-31 22:36 UTC, PJColombo commented on packages/api/test/block.test.ts
> +      type Input = inferProcedureInput<AppRouter["block"]["getAll"]>;
Move type outside of describe

2023-08-31 22:36 UTC, PJColombo commented on packages/api/test/block.test.ts
> +      type Input = inferProcedureInput<AppRouter["block"]["getByHash"]>;
Move type outside of describe

2023-08-31 22:36 UTC, PJColombo commented on packages/api/test/block.test.ts
> +      type Input = inferProcedureInput<AppRouter["block"]["getByBlockNumber"]>;
Move type outside of describe

2023-08-31 22:36 UTC, PJColombo commented on packages/api/test/blob.test.ts
> +      type Input = inferProcedureInput<AppRouter["blob"]["getAll"]>;
Move type outside of describe

2023-08-31 22:36 UTC, PJColombo commented on packages/api/test/blob.test.ts
> +      type Input = inferProcedureInput<AppRouter["blob"]["getByVersionedHash"]>;
Move type outside of describe

2023-08-31 22:36 UTC, PJColombo commented on packages/api/test/blob.test.ts
> +      type Input = inferProcedureInput<AppRouter["blob"]["getByVersionedHash"]>;
Move type outside of describe

2023-08-31 22:36 UTC, PJColombo commented on packages/api/test/blob.test.ts
> +      type Input = inferProcedureInput<AppRouter["blob"]["getByVersionedHash"]>;
Move type outside of describe

2023-08-31 22:36 UTC, PJColombo commented on packages/api/test/block.test.ts
> +  const caller = await getCaller();
Wrap within `beforeAll`

2023-08-31 22:36 UTC, PJColombo commented on packages/db/test/extensions/base.test.ts
> +    it("should upsert addresses from transactions", async () => {
There are multiple cases we should test here:
- Check both fields are set correctly for addresses (sender and receiver) being stored for the first time
- Check an address already stored as a sender/receiver doesn't get its `firstBlockNumberAsSender`/`firstBlobNumberAsReceiver` field updated if the new block number is greater.

2023-08-31 22:36 UTC, PJColombo commented on packages/db/test/extensions/stats.test.ts
> +    describe("Blob model", () => {
We should check both for insert and update cases

2023-08-31 22:36 UTC, PJColombo commented on packages/db/test/extensions/stats.test.ts
> +      it("should fill stats in a date period", async () => {
Right now it will fail if we do it, but we should check for different kind of date input formats and expect the operation to run.

2023-09-01 10:25 UTC, PabloCastellano commented on docker-compose.yml
> +    image: postgres:14.1-alpine
You are pinning 14.1 (hence downgrading the postgres version). I'd rather leave 14. (`14-alpine` is fine too)

2023-09-01 10:25 UTC, PabloCastellano commented on packages/api/test/blob.test.ts
> +    GOOGLE_STORAGE_API_ENDPOINT: "http://localhost:8080",
Try http://storage:8080

2023-09-01 10:25 UTC, PabloCastellano commented on scripts/run-integration.sh
> +$DIR/wait-for-it.sh "${DATABASE_URL}" -- echo '🟢 - Database is ready!'
I guess you want also wait until the fake-gcs-server is ready

2023-09-02 02:27 UTC, 0xGabi commented on packages/api/test/blob.test.ts
> +}));
I realize I should be setting this as env on the CI and use as much of the sane default we already configure for our envs.

2023-09-02 02:46 UTC, 0xGabi commented on packages/api/test/indexer.test.ts
> +    it("should index new data if auth", async () => {
Oh nice, well thought!

2023-09-03 10:27 UTC, PJColombo approved these changes
LGTM!

2023-09-03 10:31 UTC, merged