feat(api): expose public REST API
Blobscan/blobscan pull request #254
Opened 2024-02-25 16:03 UTC by 0xGabi

2024-02-29 02:17 UTC, PJColombo requested changes
Good work!.

Left some reviews. Most of them are cosmetic typo and rephrasing changes to the endpoints' descriptions.

2024-02-29 02:17 UTC, PJColombo commented on packages/api/src/routers/stats/getBlockDailyStats.ts
> +      summary: "get blocks time series stats",
```suggestion
      summary: "retrieves blocks time series stats.",
```

2024-02-29 02:17 UTC, PJColombo commented on packages/api/src/routers/stats/getBlockOverallStats.ts
> +      summary: "get blocks overall stats",
```suggestion
      summary: "retrieves blocks overall stats.",
```

2024-02-29 02:17 UTC, PJColombo commented on packages/api/src/routers/stats/getTransactionDailyStats.ts
> +      summary: "get transactions time series stats",
```suggestion
      summary: "retrieves transactions time series stats.",
```

2024-02-29 02:17 UTC, PJColombo commented on packages/api/src/routers/stats/getTransactionOverallStats.ts
> +      summary: "get transactions overall stats",
```suggestion
      summary: "retrieves transactions overall stats.",
```

2024-02-29 02:17 UTC, PJColombo commented on packages/api/src/routers/tx/getAll.ts
> +      summary: "get transactions",
```suggestion
      summary: "retrieves all blob transactions.",
```

2024-02-29 02:17 UTC, PJColombo commented on packages/api/src/routers/tx/getByHash.ts
> +      summary: "get tx info",
```suggestion
      summary: "retrieves transaction details for given transaction hash.",
```

2024-02-29 02:17 UTC, PJColombo commented on packages/api/src/routers/indexer/handleReorgedSlot.ts
> +        "it marks all blocks with slot greater than the new head slot as reorged.",
```suggestion
        "marks all blocks with slot greater than the new head slot as reorged.",
```

2024-02-29 02:17 UTC, PJColombo commented on packages/api/src/routers/blockchain-sync-state/updateState.ts
> +      summary: "update the blockchain sync state",
```suggestion
      summary: "updates the blockchain sync state.",
```

2024-02-29 02:17 UTC, PJColombo commented on packages/api/src/routers/blockchain-sync-state/getState.ts
> +      summary: "get the current blockchain sync state",
```suggestion
      summary: "retrieves the blockchain sync state.",
```

2024-02-29 02:17 UTC, PJColombo commented on packages/api/src/routers/blob/getAll.ts
> +      summary: "get blobs",
```suggestion
      summary: "retrieves all blobs.",
```

2024-02-29 02:17 UTC, PJColombo commented on packages/api/src/routers/blob/getByVersionedHash.ts
> +      summary: "get blob info",
```suggestion
      summary: "retrieves blob details for given versioned hash.",
```

2024-02-29 02:17 UTC, PJColombo commented on packages/api/src/routers/blob/getByVersionedHash.ts
>  export const getByVersionedHash = publicProcedure
Maybe we can create an unified procedure called `getByBlobId` similar to the block id I mentioned below.

The blob id could be the versioned hash or the commitment.

Wdyt?

2024-02-29 02:17 UTC, PJColombo commented on packages/api/src/routers/block/getAll.ts
> +      summary: "get blocks",
```suggestion
      summary: "retrieves all blocks.",
```

2024-02-29 02:17 UTC, PJColombo commented on packages/api/src/routers/indexer/indexData.ts
> +      summary: "index data in the database",
```suggestion
      summary: "indexes data in the database.",
```

2024-02-29 02:17 UTC, PJColombo commented on packages/api/src/app-router.ts
> +        summary: "connection healthcheck",
```suggestion
        summary: "connection healthcheck.",
```

2024-02-29 03:25 UTC, 0xGabi commented on apps/rest-api-server/src/env.ts
> +      BLOBSCAN_API_BASE_URL: z
I was resolving this issue: https://github.com/Blobscan/blobscan/issues/205

I modified the openapi configuration here as well:https://github.com/Blobscan/blobscan/blob/public-apis/apps/rest-api-server/src/openapi.ts#L12

2024-02-29 03:28 UTC, 0xGabi commented on apps/web/src/pages/blob/[hash].tsx
> +      versioned_hash: versionedHash,
Maybe is not relevant. Though I saw snake case was the convention on both BeaconAPI and Blockscout.

2024-02-29 03:29 UTC, 0xGabi commented on packages/api/src/routers/block/getByHash.ts
> +      summary: "get block info",
Yes, I agree.

2024-03-02 01:20 UTC, PJColombo commented on apps/web/src/pages/blob/[hash].tsx
> +      versioned_hash: versionedHash,
Oh, I see. Let's rename it to `hash` then.

2024-03-02 01:22 UTC, PJColombo commented on apps/rest-api-server/src/env.ts
> +      BLOBSCAN_API_BASE_URL: z
Got it. I forgot that we're gonna have an exposed api for each chain.

We can resolve this conversation then.

2024-03-02 05:24 UTC, Mandog1120 commented
a34ed3ae13dd84bccbaea7573bf0120530da830d

2024-03-04 20:08 UTC, PabloCastellano approved these changes

2024-03-04 20:08 UTC, PabloCastellano commented on apps/rest-api-server/src/openapi.ts
> +  baseUrl: `${env.BLOBSCAN_API_BASE_URL}/api`,
:+1:

2024-03-05 15:32 UTC, merged