Display Swarm data expiry
Blobscan/blobscan pull request #355
Opened 2024-03-29 21:37 UTC by 0xGabi

part of #338

2024-03-29 23:13 UTC, PJColombo requested changes
Good job.

I left some review comments with some major changes I think we should do

2024-03-29 23:13 UTC, PJColombo commented on packages/api/src/routers/swarm-state/getState.ts
I wouldn't instantiate the bee debug again when we already have it in the swarm storage and I wouldn't expose it either. I think the bee client should be kept encapsulated within the swarm storage. 

I'm thinking maybe it would make more sense to add a new method to the `SwarmStorage` class that returns the info related to a stamp batch. It could be `getStampBatchInfo(batchLabel: string): BatchInfo | null`. That way we keep the client encapsulated and we provided the necessary data to the consumer of the swarm storage 

Within this procedure, we can get the swarm storage from the blob storage manager via `getStorage` and then if we do have the swarm storage I would call the previous method to get the info and then return the ttl

2024-03-29 23:13 UTC, PJColombo commented on apps/web/src/components/ExplorerDetails.tsx
> +            name="Swarm data expiry"
```suggestion
            name="Swarm data expiration"
```

2024-03-30 04:31 UTC, 0xGabi commented on packages/dayjs/index.ts
> +import duration from "dayjs/plugin/duration";
In this case `relativeTime` is not what we need. Because `ttl` is not a time. Is the amount of seconds that the batch will be available.

2024-03-30 09:43 UTC, PJColombo commented on packages/dayjs/index.ts
> +import duration from "dayjs/plugin/duration";
@0xGabi, I think we can get it like this then:

`dayjs().to(dayjs().add(ttl, "second"))`

2024-03-30 19:57 UTC, merged