fix: rename `rollup` field
Blobscan/blobscan pull request #455
Opened 2024-07-29 15:16 UTC by PJColombo

### Checklist

- [ ] My change requires a documentation update, and I have done it.
- [ ] I have added tests to cover my changes.
- [ ] I have filled out the description and linked the related issues.

### Description

#### Motivation and Context (Optional)

### Related Issue (Optional)

### Screenshots (if appropriate):

2024-07-30 08:56 UTC, PabloCastellano reviewed
I left you a suggestion.

2024-07-30 08:56 UTC, PabloCastellano commented on packages/api/src/utils/schemas.ts
> +  "unknown",
"unknown" would make sense for rollups.

For categories I believe "other" or "uncategorized" are better choices.

2024-07-31 09:03 UTC, PabloCastellano requested changes
Let's discuss a way for filtering blobs that don't belong to a rollup without introducing a breaking change for our API users

2024-08-06 08:59 UTC, closed without merging

2024-08-06 09:01 UTC, PJColombo commented
Closing this as it was decided to keep `rollup` enum and have a new `category` enum