feat: Add Loading component and use it in SearchInput
Blobscan/blobscan pull request #464
Opened 2024-07-31 14:44 UTC by luis-herasme

### Checklist

- [ ] My change requires a documentation update, and I have done it.
- [ ] I have added tests to cover my changes.
- [x] I have filled out the description and linked the related issues.

### Description

A `Loading` component is added to provide a loading animation while fetching search results in the `SearchInput` component. This improves the user experience by indicating that the search is in progress.
### Related Issue

#289

### Screenshots:
![image](https://github.com/user-attachments/assets/3889a572-ff4f-4ea7-9abc-8d4b74c6c487)

2024-08-01 15:24 UTC, PJColombo requested changes
Nice job!.

Left a comment.

Can we also display a "No results found" message in the search results modal when no results are returned? Currently, the loading spinner appears and disappears too quickly, which might confuse users as there is no indication whether results were found.

2024-08-01 15:24 UTC, PJColombo commented on apps/web/src/components/Loading.tsx
There's no need to create a component wrapping a svg. We configured [`svgr`](https://react-svgr.com) for that which does it automatically.

Let's add this to an svg file to [`/src/icons`](https://github.com/Blobscan/blobscan/tree/next/apps/web/src/icons) which is the folder that `svgo` uses to optimise svgs images

2024-08-01 15:27 UTC, PJColombo commented on apps/web/src/components/Loading.tsx
Also. Can you run `pnpm svg:format` from the `web` app package to optimise the images once you add them?.  

We need to add this to the pipeline to do it automatically

2024-08-01 16:41 UTC, luis-herasme commented
> Currently, the loading spinner appears and disappears too quickly,

I improved this after the last commit. Now, we show the loading spinner while debouncing.

2024-08-01 16:42 UTC, luis-herasme commented
> Currently, the loading spinner appears and disappears too quickly,

I improved this after the last commit. Now, we show the loading spinner while debouncing.

2024-08-01 16:44 UTC, luis-herasme commented
No results found component:
![image](https://github.com/user-attachments/assets/4e4b5767-fbf8-41af-a09d-f70f6f03db71)

2024-08-02 04:47 UTC, PJColombo approved these changes
LGTM!

One last thing: let's add a changeset

2024-08-02 13:50 UTC, merged