Fix block stats
Blobscan/blobscan pull request #515
Opened 2024-08-21 16:55 UTC by luis-herasme

2024-08-21 17:20 UTC, PabloCastellano requested changes
Still failing. Check https://blobscan-staging-git-fix-block-stats-blossom-labs.vercel.app/stats/block

![image](https://github.com/user-attachments/assets/f4236252-7527-49ed-8d32-4a637f304781)

2024-08-21 18:03 UTC, PJColombo requested changes
We’re currently rounding the metrics instead of displaying the actual values.

To address this, I suggest updating the `convertWei` function to handle decimal values. As shown by the errors, there are cases where we encounter wei values with decimals, particularly when dealing with averages.

Additionally, I noticed that we’re always converting values to big integers before passing them to `convertWei`. Instead of doing this, we could let the function itself handle the normalization of input parameters, as it was done prior to the changes in PR #493.

2024-08-27 01:04 UTC, PJColombo approved these changes
LGTM

2024-08-27 14:21 UTC, PabloCastellano approved these changes
LGTM!

2024-08-27 14:22 UTC, PabloCastellano commented on .changeset/light-wombats-try.md
> +Update DailyAvgBlobGasPriceChart to round average gas prices
Only missing thing is updating this description

2024-08-27 14:40 UTC, merged