Ether unit allow string number
Blobscan/blobscan pull request #526
Opened 2024-08-28 23:48 UTC by luis-herasme

### Checklist

- [ ] My change requires a documentation update, and I have done it.
- [ ] I have added tests to cover my changes.
- [ x ] I have filled out the description and linked the related issues.

### Description
Updated `EtherUnitDisplay` to accept `bigint`, `number`, or `string` for `amount` prop

### Related Issue
Closes #521

2024-08-31 13:14 UTC, PJColombo requested changes
I think we should refocus this PR on removing the rounding logic to preserve precision.

wdyt?

2024-08-31 13:14 UTC, PJColombo commented on packages/eth-format/index.ts
Can we also allow [`prettyFormatWei`](https://github.com/Blobscan/blobscan/blob/876db84843aa24dd8b3b999d39d28294d20f49bb/packages/eth-format/index.ts#L33) to receive string and number?

This change would help us avoid rounding the [value] (https://github.com/Blobscan/blobscan/blob/876db84843aa24dd8b3b999d39d28294d20f49bb/apps/web/src/components/Cards/MetricCard.tsx#L69) in the metric card as well.

2024-08-31 13:24 UTC, PJColombo commented on .changeset/chilled-frogs-battle.md
No need to add a changeset as this change doesn't affect the current behaviour as it's just a refactoring.

2024-09-02 14:10 UTC, luis-herasme commented on packages/eth-format/index.ts
> +  if (typeof wei === "number") {
Done [d2d2882](https://github.com/Blobscan/blobscan/pull/526/commits/d2d28825fa274d08d4314c31dc0f0bfb287aca9f)

2024-09-02 14:16 UTC, luis-herasme commented on packages/eth-format/index.ts
Done [5075e9c](https://github.com/Blobscan/blobscan/pull/526/commits/5075e9c85f1ed35d3cd1c9cffa4d8873847d1396)

2024-09-02 14:16 UTC, luis-herasme commented on .changeset/chilled-frogs-battle.md
Done [70574ef](https://github.com/Blobscan/blobscan/pull/526/commits/70574efbf73ccc77d63ef27ddc4dbe2dbb101452)

2024-09-02 17:42 UTC, PJColombo approved these changes
LGTM!

2024-09-03 10:30 UTC, PabloCastellano reviewed
Can you add some unit tests for countIntegerDigits?

2024-09-03 13:53 UTC, PabloCastellano approved these changes

2024-09-03 13:54 UTC, merged