fix(web): add a "reorg" label to reorged slots/blocks search results
Blobscan/blobscan pull request #582
Opened 2024-09-23 00:15 UTC by luis-herasme

### Checklist

- [ ] My change requires a documentation update, and I have done it.
- [ ] I have added tests to cover my changes.
- [x] I have filled out the description and linked the related issues.

### Description
Adds a `reorg` label to reorged slots/blocks search results

### Related Issue
Closes #406

### Screenshots
Before:
![image](https://github.com/user-attachments/assets/44bb9f87-d6f6-464b-8bc8-2c71d5a161b9)

After:
![image](https://github.com/user-attachments/assets/bb3687d8-e735-42e6-8a8e-91c8cf6d68e4)
![image](https://github.com/user-attachments/assets/446cc88b-8bc2-44e8-9c7d-968bfaa82e59)

2024-09-23 07:22 UTC, xFJA approved these changes

2024-10-11 16:55 UTC, PJColombo requested changes
Nice work.

Left a few comments

2024-10-11 16:55 UTC, PJColombo commented on apps/web/src/components/Badges/Badge.tsx
wdyt about using an optional variant instead of creating a none variant to explicitly represent the absence of a style value?

2024-10-11 16:55 UTC, PJColombo commented on .changeset/strong-masks-remain.md
> +A new label "reorg" has been added to the reorged slots/blocks search results
```suggestion
Added a new label "reorg" to the reorged slots/blocks search results
```

2024-10-11 16:55 UTC, PJColombo commented on apps/web/src/components/SearchInput/SearchResults.tsx
> +              reorg
```suggestion
              Reorg
```

2024-10-13 19:26 UTC, luis-herasme commented on apps/web/src/components/Badges/Badge.tsx
[f965994](https://github.com/Blobscan/blobscan/pull/582/commits/f96599484da78f4a233f8b6af8d7609399cc0887)

2024-10-27 16:19 UTC, PJColombo requested changes
Can we resolve the type-check problem? The GitHub actions job is throwing an error

Feel free to merge this once resolved.

2024-10-28 22:11 UTC, PJColombo approved these changes
I’ve pushed a commit to fix some search unit tests. All jobs are now passing, so feel free to merge it.

2024-10-28 22:12 UTC, merged