Remove blob propagator enabled
Blobscan/blobscan pull request #628
Opened 2024-11-09 19:19 UTC by luis-herasme

### Checklist

- [ ] My change requires a documentation update, and I have done it.
- [ ] I have added tests to cover my changes.
- [x] I have filled out the description and linked the related issues.

### Description
Removes `BLOB_PROPAGATOR_ENABLED` variable

### Related Issue (Optional)
Closes  #513

2024-11-10 07:51 UTC, xFJA commented on .changeset/eighty-lobsters-rest.md
> +Removed BLOB_PROPAGATOR_ENABLED variable
```suggestion
Removed `BLOB_PROPAGATOR_ENABLED` variable.
```

2024-11-10 07:52 UTC, xFJA approved these changes

2024-11-16 13:03 UTC, PJColombo requested changes
Can we take a look at the `type-check` job? It failed

2024-11-17 06:41 UTC, PJColombo commented
Let's also remove this [UT](https://github.com/Blobscan/blobscan/blob/4a3e50c60f8a7918717f112e30ee1052bd1e357e/packages/api/test/indexer.test.ts#L443) as it's not longer necessary

2024-11-25 14:09 UTC, merged