Add help tooltip block
Blobscan/blobscan pull request #665
Opened 2024-12-04 15:52 UTC by luis-herasme

### Checklist

- [ ] My change requires a documentation update, and I have done it.
- [ ] I have added tests to cover my changes.
- [x] I have filled out the description and linked the related issues.

### Description
Adds a help tooltip to each field in the block details page

### Related Issue
#433

### Screenshots
<img width="494" alt="image" src="https://github.com/user-attachments/assets/6e8b1366-930d-432c-8d34-d3070ab32314">

2024-12-07 10:39 UTC, PJColombo requested changes
Left a few comments.

2024-12-07 10:39 UTC, PJColombo commented on apps/web/src/pages/block/[id].tsx
In this case, since both functionalities will always be used together, I suggest expanding the `InfoGrid` props to include a new prop called `helpText`, which accepts a `ReactNode`. This approach would eliminate the need to wrap every field in an `InfoField` component.

2024-12-07 10:39 UTC, PJColombo commented on apps/web/src/pages/block/[id].tsx
> +          <InfoField description="The size of the Blob.">Blob size</InfoField>
```suggestion
          <InfoField description="Total amount of size used for blobs in this block.">Blob size</InfoField>
```

2024-12-07 10:39 UTC, PJColombo commented on apps/web/src/pages/block/[id].tsx
> +          <InfoField description="The gas price of the blob.">
```suggestion
          <InfoField description="The cost per unit of blob gas used by the blobs in this block.">
```

2024-12-07 10:39 UTC, PJColombo commented on apps/web/src/pages/block/[id].tsx
> +          <InfoField description="The gas used by the blob.">
```suggestion
          <InfoField description="The total blob gas used by the blobs in this block, along with its percentage relative to the total blob gas limit and the blob gas target (~0.375 MB).">
```

2024-12-07 10:39 UTC, PJColombo commented on apps/web/src/pages/block/[id].tsx
> +          <InfoField description="The gas limit of the blob.">
```suggestion
          <InfoField description="The maximum blob gas limit for this block.">
```

2024-12-07 10:39 UTC, PJColombo commented on apps/web/src/pages/block/[id].tsx
> +          <InfoField description="The gas that the blob would have used if it was executed as calldata.">
```suggestion
          <InfoField description="The total gas that would have been used in this block if the blobs had been sent as calldata.">
```

2024-12-07 10:39 UTC, PJColombo commented on apps/web/src/pages/block/[id].tsx
> +          <InfoField description="The block height is the number of blocks preceding the current block.">
Maybe it’s just me, but I find this a little bit confusing. Based on this description, does having block number 10 mean that 10 blocks precede it?

I suggest the following alternative description:

```suggestion
          <InfoField description="Also referred to as Block Number, the block height represents the length of the blockchain and increases with each newly added block.">
```

2024-12-07 14:49 UTC, luis-herasme commented on apps/web/src/icons/info.svg
Done [02dd04b](https://github.com/Blobscan/blobscan/pull/665/commits/02dd04b1a9db9a910c0f2ae5a24e74650c6c1dea)

2024-12-07 15:33 UTC, luis-herasme commented on apps/web/src/pages/block/[id].tsx
Done [d2094c0](https://github.com/Blobscan/blobscan/pull/665/commits/d2094c00c731cf13f64997a36f66a5b6aa604ba6)

2024-12-11 05:04 UTC, PabloCastellano approved these changes
I reviewed the texts using chatgpt. Other than that, LGTM!

2024-12-15 05:03 UTC, xFJA approved these changes

2024-12-16 14:26 UTC, luis-herasme commented on apps/web/src/pages/block/[id].tsx
> +          "The total blob gas used by the blobs in this block, along with its percentage relative to the total blob gas limit and the blob gas target (~0.375 MB).",
Done [23a0f32](https://github.com/Blobscan/blobscan/pull/665/commits/23a0f322ff3a5053cd2ef841ac8bb19528d1c785)

2025-01-10 15:28 UTC, PJColombo approved these changes
LGTM!

2025-01-13 04:14 UTC, merged